import type { Metadata } from 'next';
import { Inter_Tight } from 'next/font/google';
import styles from './layout.module.scss';
import './globals.scss';
import Image from 'next/image';
import Link from 'next/link';
import {
  FaFacebookF,
  FaInstagram,
  FaLinkedin,
  FaYoutube,
} from 'react-icons/fa';
import { UnstyledLink } from './components/UnstyledLink';

const interTight = Inter_Tight({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Save Our Salmon',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${interTight.className}`}>
        <div className={styles.layout}>
          <nav className={styles.nav}>
            <div className={styles.navLayout}>
              <UnstyledLink href="/">
                <Image
                  src="/SOSTA color gray.png"
                  alt="Save Our Salmon"
                  width={100}
                  height={75}
                  className={styles.logo}
                />
              </UnstyledLink>
              {/* <div>SAVE OUR SALMON</div> */}
              <div className={styles.links}>
                <Link href="/about">About</Link>
                <Link href="/murals">Murals</Link>
                <Link href="/events">Events</Link>
                {/* <Link href="/resources">Resources</Link> */}
                <Link href="/shop">Shop</Link>
              </div>
            </div>
          </nav>
          <div>{children}</div>
          <div className={styles.footer}>
            <div className={styles.wave1}></div>
            <div className={styles.wave2}></div>
            <div className={styles.wave3}></div>
            <div className={styles.wave4}>
              <Image
                className={styles.footerLogo}
                src="/SOSTA color white.png"
                alt="Logo"
                width="125"
                height="125"
              />
              <div className={styles.footerContent}>
                <div className={styles.subscribe}>
                  Subscribe to our newsletter!
                </div>
                <div className={styles.inputWrapper}>
                  <input />
                  <button>Enter</button>
                </div>
                <div className={styles.socials}>
                  <UnstyledLink href="https://instagram.com" target="_blank">
                    <div className={styles.social}>
                      <FaInstagram />
                    </div>
                  </UnstyledLink>
                  <UnstyledLink href="https://facebook.com" target="_blank">
                    <div className={styles.social}>
                      <FaFacebookF />
                    </div>
                  </UnstyledLink>
                  <UnstyledLink href="https://youtube.com" target="_blank">
                    <div className={styles.social}>
                      <FaYoutube />
                    </div>
                  </UnstyledLink>
                  <UnstyledLink href="https://linkedin.com" target="_blank">
                    <div className={styles.social}>
                      <FaLinkedin />
                    </div>
                  </UnstyledLink>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
